The dimension of y_tensor is torch.Size([10201, 2]).
The dimension of y_expanded is torch.Size([500, 10201, 2]) after expanding.
The zero coordinate of y_expanded is temporal and the first coordinate is space.
The dimensions of the initial conditions are: (500, 101)
The dimensions of the solutions are: (500, 101, 101)
The dimension of u_tensor is torch.Size([500, 101]).
The dimension of u_expanded is torch.Size([500, 10201, 101]) after expanding.
The loaded solution dataset has dimension (500, 101, 101),
	 while the arranged linearized dataset has dimension (500, 10201).
The dimension of s_tensor is torch.Size([500, 10201]).
The dimension of s_expanded is torch.Size([500, 10201, 1]) after expanding.
The training dataset has 4080400 samples, while the train_loader has 409 batches.
The training dataset has 1020100 samples, while the train_loader has 511 batches.
cpu
Epoch 1
Epoch 1 Time: 74.56 seconds
Epoch 2
Epoch 2 Time: 51.11 seconds
Epoch 3
Epoch 3 Time: 51.15 seconds
Epoch 4
Epoch 4 Time: 48.49 seconds
Epoch 5
Epoch 5 Time: 48.85 seconds
Epoch 6
Epoch 6 Time: 51.88 seconds
Epoch 7
Epoch 7 Time: 49.56 seconds
Epoch 8
Epoch 8 Time: 51.01 seconds
Epoch 9
Epoch 9 Time: 49.95 seconds
Epoch 10
Epoch 10 Time: 49.42 seconds
ERROR:fipy:Uncaught exception:
Traceback (most recent call last):
  File "/qfs/people/weiz828/DON/1d_train/1dd.py", line 332, in <module>
    model.load_state_dict(torch.load(model_params_best, map_location=torch.device(device), weights_only=True))
                                     ^^^^^^^^^^^^^^^^^
NameError: name 'model_params_best' is not defined. Did you mean: 'model_params_final'?
